#!/usr/bin/env php
<?php
/**
 * @copyright   Copyright (c) http://careyshop.cn All rights reserved.
 *
 * CareyShop    命令行入口文件
 *
 * @author      zxm <252404501@qq.com>
 * @date        2020/7/20
 */

namespace think;

// 加载基础文件
require __DIR__ . '/vendor/autoload.php';

// 应用初始化
(new App())->console->run();
